-- Generated by scripts/build-seed.mjs — sample Nordaloom catalogue.
-- Re-running replaces the catalogue (and any carts referencing it).
begin;
delete from public.products;
delete from public.categories;

insert into public.categories (slug, name, tagline, description, image, sort_order) values ('sweaters', 'Sweaters', 'The ones you reach for first', 'Crewnecks, cables, rollnecks and chunky ribs. Cut to be worn for years and to soften with every winter.', 'products/sweater-12.webp', 1);
insert into public.categories (slug, name, tagline, description, image, sort_order) values ('cardigans', 'Cardigans', 'A layer for every room', 'Buttoned, cropped, open and oversized — cardigans to wear over a shirt, a dress or another sweater from October to April.', 'products/cardigan-05.webp', 2);
insert into public.categories (slug, name, tagline, description, image, sort_order) values ('hats', 'Hats', 'Warm ears, all season', 'Ribbed beanies and slouchy knits in the same yarns as our sweaters.', 'products/hat-02.webp', 3);
insert into public.categories (slug, name, tagline, description, image, sort_order) values ('scarves', 'Scarves', 'Wrapped twice, at least', 'Long scarves, airy mohair and wide wraps generous enough to double as a shawl on a cold train platform.', 'products/scarf-03.webp', 4);
insert into public.categories (slug, name, tagline, description, image, sort_order) values ('mittens', 'Mittens', 'Warm hands, bright patterns', 'Patterned mittens in the Latvian tradition — the one piece of knitwear where we let colour run wild.', 'products/mittens-02.webp', 5);
insert into public.categories (slug, name, tagline, description, image, sort_order) values ('socks', 'Socks', 'Made to be worn out', 'Ribbed everyday socks, lace-cable socks and patterned pairs for a cold floor on a winter morning.', 'products/socks-03.webp', 6);
insert into public.categories (slug, name, tagline, description, image, sort_order) values ('blankets', 'Blankets', 'For long evenings', 'Woven wool throws with fringed edges, and chunky knitted blankets heavy enough to feel like a hug.', 'products/blanket-01.webp', 7);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('kapa-crewneck', 'sweaters', 'Kāpa Crewneck', 'Our everyday raglan crewneck', 'Named after the dunes along the Kurzeme coast, Kāpa is the sweater we''d keep if we could only have one. A clean raglan shape in smooth lambswool, with ribbed cuffs and hem and a neat round neckline that holds its form wash after wash.

Mid-weight and quietly warm, it sits as well under a coat in January as it does on its own on a cool May evening.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Regular fit — take your usual size', 'Raglan sleeves, ribbed hem and cuffs', 'Mid-weight, approx. 480 g (size M)', 'Knitted in small batches in Latvia']::text[], 15900, '[{"name":"Chestnut","hex":"#7b4a33"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Moss","hex":"#6b7358"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-07.webp']::text[], true, false, true, 1);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'kapa-crewneck'), 'Chestnut', 'XS', 1, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Chestnut', 'S', 1, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Chestnut', 'M', 0, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Chestnut', 'L', 6, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Chestnut', 'XL', 7, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Oat', 'XS', 2, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Oat', 'S', 13, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Oat', 'M', 7, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Oat', 'L', 6, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Oat', 'XL', 4, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Charcoal', 'XS', 0, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Charcoal', 'S', 0, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Charcoal', 'M', 9, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Charcoal', 'L', 3, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Charcoal', 'XL', 10, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Moss', 'XS', 6, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Moss', 'S', 10, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Moss', 'M', 0, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Moss', 'L', 0, null),
  ((select id from public.products where slug = 'kapa-crewneck'), 'Moss', 'XL', 12, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('priede-fisherman-rollneck', 'sweaters', 'Priede Fisherman Rollneck', 'Ribbed from rollneck to hem', 'A proper cold-weather sweater. Priede is knitted in a fisherman rib from a soft, lightly spun wool that keeps its loft and shrugs off wind. The rollneck is deep enough to fold twice or pull up over your chin, and the body is long enough to tuck in.

The kind of sweater that replaces a jacket on a dry winter day.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Relaxed, longer fit — size down for a closer fit', 'Fisherman rib throughout', 'Heavyweight, approx. 850 g (size M)', 'Knitted in small batches in Latvia']::text[], 19800, '[{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Juniper","hex":"#3f5245"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-08.webp']::text[], true, false, true, 2);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Undyed Ecru', 'XS', 4, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Undyed Ecru', 'S', 5, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Undyed Ecru', 'M', 5, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Undyed Ecru', 'L', 1, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Undyed Ecru', 'XL', 3, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Juniper', 'XS', 1, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Juniper', 'S', 1, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Juniper', 'M', 14, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Juniper', 'L', 0, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Juniper', 'XL', 9, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Charcoal', 'XS', 1, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Charcoal', 'S', 12, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Charcoal', 'M', 10, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Charcoal', 'L', 12, null),
  ((select id from public.products where slug = 'priede-fisherman-rollneck'), 'Charcoal', 'XL', 6, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('gauja-cable-crew', 'sweaters', 'Gauja Cable Crew', 'Three winding cables down the front', 'The cables on Gauja twist and turn like the river it''s named after: three deep cable panels down the front, framed by ribbing, in a round, full-bodied wool that gives every stitch real depth.

A sweater with presence, cut with enough room in the body for a shirt underneath.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Regular fit', 'Three cable panels on the front, ribbed crew neck', 'Heavyweight, approx. 780 g (size M)', 'Knitted in small batches in Latvia']::text[], 20900, '[{"name":"Forest Green","hex":"#3f5a3c"},{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-09.webp']::text[], false, false, true, 3);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Forest Green', 'XS', 6, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Forest Green', 'S', 1, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Forest Green', 'M', 7, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Forest Green', 'L', 7, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Forest Green', 'XL', 1, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Undyed Ecru', 'XS', 1, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Undyed Ecru', 'S', 1, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Undyed Ecru', 'M', 1, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Undyed Ecru', 'L', 6, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Undyed Ecru', 'XL', 4, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Oat', 'XS', 6, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Oat', 'S', 0, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Oat', 'M', 11, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Oat', 'L', 11, null),
  ((select id from public.products where slug = 'gauja-cable-crew'), 'Oat', 'XL', 4, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('ezers-cable-crew', 'sweaters', 'Ezers Cable Crew', 'All-over cables in a deep lake teal', 'Ezers is covered in narrow braided cables from shoulder to hem, knitted in a dense wool the colour of a lake on a grey morning. The neck is a short, snug ribbed crew and the hem sits at the hip, so it looks as right with work trousers as with jeans.

Warm enough to wear on its own on a cold, clear day.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Regular fit', 'All-over braided cables', 'Heavyweight, approx. 750 g (size M)', 'Knitted in small batches in Latvia']::text[], 21500, '[{"name":"Deep Teal","hex":"#2f4a4d"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-02.webp']::text[], false, false, true, 4);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Deep Teal', 'XS', 8, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Deep Teal', 'S', 10, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Deep Teal', 'M', 12, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Deep Teal', 'L', 8, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Deep Teal', 'XL', 3, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Charcoal', 'XS', 6, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Charcoal', 'S', 10, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Charcoal', 'M', 2, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Charcoal', 'L', 9, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Charcoal', 'XL', 5, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Oat', 'XS', 5, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Oat', 'S', 1, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Oat', 'M', 4, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Oat', 'L', 3, null),
  ((select id from public.products where slug = 'ezers-cable-crew'), 'Oat', 'XL', 3, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('rudens-aran-sweater', 'sweaters', 'Rudens Aran Sweater', 'Cables and diamonds in autumn burgundy', 'Rudens (autumn) is our aran: cables, diamonds and textured panels worked across the whole front and down the sleeves, in a deep burgundy that looks almost black by candlelight.

A heavy, generous sweater for the darkest months of the year.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Relaxed fit', 'Aran cables and diamond panels', 'Heavyweight, approx. 900 g (size M)', 'Knitted in small batches in Latvia']::text[], 22900, '[{"name":"Burgundy","hex":"#5b2327"},{"name":"Undyed Ecru","hex":"#ede6d6"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-05.webp']::text[], false, false, true, 5);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Burgundy', 'XS', 12, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Burgundy', 'S', 14, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Burgundy', 'M', 11, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Burgundy', 'L', 15, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Burgundy', 'XL', 10, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Undyed Ecru', 'XS', 1, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Undyed Ecru', 'S', 1, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Undyed Ecru', 'M', 8, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Undyed Ecru', 'L', 3, null),
  ((select id from public.products where slug = 'rudens-aran-sweater'), 'Undyed Ecru', 'XL', 3, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('suna-long-cable-sweater', 'sweaters', 'Sūna Long Cable Sweater', 'Oversized and long, with a single cable', 'Sūna (moss) is long, loose and very soft: an oversized sweater that falls to the upper thigh, with one cable running down the centre and dropped shoulders that let the sleeves pool at the wrist.

Wear it with leggings on a slow Sunday, or belted over a skirt.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Oversized, long fit — size down for less volume', 'Central cable, dropped shoulders', 'Mid-weight, approx. 620 g (size M)', 'Knitted in small batches in Latvia']::text[], 19500, '[{"name":"Bottle Green","hex":"#2f5146"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Fog Grey","hex":"#b9b8b0"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-03.webp']::text[], false, true, true, 6);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Bottle Green', 'XS', 9, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Bottle Green', 'S', 0, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Bottle Green', 'M', 11, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Bottle Green', 'L', 2, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Bottle Green', 'XL', 10, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Oat', 'XS', 6, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Oat', 'S', 11, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Oat', 'M', 1, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Oat', 'L', 6, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Oat', 'XL', 11, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Fog Grey', 'XS', 0, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Fog Grey', 'S', 7, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Fog Grey', 'M', 15, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Fog Grey', 'L', 1, null),
  ((select id from public.products where slug = 'suna-long-cable-sweater'), 'Fog Grey', 'XL', 9, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('berzs-chunky-v-neck', 'sweaters', 'Bērzs Chunky V-Neck', 'A chunky rib V-neck in undyed ecru', 'Bērzs (birch) is a relaxed V-neck in a thick fisherman rib, knitted from undyed wool that keeps the soft, creamy colour of the fleece. The deep V sits comfortably over a T-shirt or a collar, and the long sleeves are made to be pushed up.

Chunky without being heavy.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Relaxed fit', 'Fisherman rib, deep V-neck', 'Mid-weight, approx. 600 g (size M)', 'Knitted in small batches in Latvia']::text[], 17500, '[{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Birch","hex":"#cfc6b6"},{"name":"Night Blue","hex":"#2f3a4d"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-04.webp']::text[], false, false, true, 7);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Undyed Ecru', 'XS', 6, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Undyed Ecru', 'S', 5, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Undyed Ecru', 'M', 7, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Undyed Ecru', 'L', 15, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Undyed Ecru', 'XL', 4, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Birch', 'XS', 3, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Birch', 'S', 8, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Birch', 'M', 1, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Birch', 'L', 15, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Birch', 'XL', 8, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Night Blue', 'XS', 0, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Night Blue', 'S', 0, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Night Blue', 'M', 0, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Night Blue', 'L', 5, null),
  ((select id from public.products where slug = 'berzs-chunky-v-neck'), 'Night Blue', 'XL', 15, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('smilga-fisherman-sweater', 'sweaters', 'Smilga Fisherman Sweater', 'Oversized fisherman rib in flecked oat', 'Smilga is named after the bent grass on the dunes, and its flecked oat colour comes from tiny darker fibres spun into the yarn. It''s an oversized crew in a springy fisherman rib, with long sleeves and a soft, slightly rolled neckline.

The sweater to pull on first thing and forget you''re wearing.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Oversized fit — take your usual size for a slouchy look', 'Fisherman rib, flecked yarn', 'Mid-weight, approx. 680 g (size M)', 'Knitted in small batches in Latvia']::text[], 18500, '[{"name":"Flecked Oat","hex":"#d8d0c2"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-01.webp']::text[], false, false, true, 8);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Flecked Oat', 'XS', 6, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Flecked Oat', 'S', 6, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Flecked Oat', 'M', 9, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Flecked Oat', 'L', 13, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Flecked Oat', 'XL', 0, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Charcoal', 'XS', 10, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Charcoal', 'S', 1, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Charcoal', 'M', 0, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Charcoal', 'L', 14, null),
  ((select id from public.products where slug = 'smilga-fisherman-sweater'), 'Charcoal', 'XL', 3, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('rudzi-chunky-rib-sweater', 'sweaters', 'Rudzi Chunky Rib Sweater', 'Boxy chunky rib with dropped shoulders', 'Rudzi (rye) is a short, boxy sweater in a chunky rib, in the warm taupe of ripe rye. Dropped shoulders and wide sleeves give it an easy shape; turn the cuffs back once for the look in the photo.

Pairs well with high-waisted trousers and long skirts.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Boxy, slightly cropped fit', 'Chunky rib, dropped shoulders', 'Mid-weight, approx. 560 g (size M)', 'Knitted in small batches in Latvia']::text[], 16900, '[{"name":"Taupe","hex":"#9c8b74"},{"name":"Undyed Ecru","hex":"#ede6d6"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/cardigan-01.webp']::text[], false, false, true, 9);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Taupe', 'XS', 8, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Taupe', 'S', 9, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Taupe', 'M', 6, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Taupe', 'L', 14, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Taupe', 'XL', 6, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Undyed Ecru', 'XS', 11, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Undyed Ecru', 'S', 9, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Undyed Ecru', 'M', 1, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Undyed Ecru', 'L', 12, null),
  ((select id from public.products where slug = 'rudzi-chunky-rib-sweater'), 'Undyed Ecru', 'XL', 7, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('rits-merino-fine-knit', 'sweaters', 'Rīts Merino Fine Knit', 'Fine-gauge merino for layering', 'Rīts (morning) is a fine, smooth merino crewneck for days that start cold and end mild. Extra-fine fibres mean it sits comfortably against the skin, and the close knit keeps its shape under jackets and coats.

It''s the sweater to wear to work, then on to dinner.', '100% extra-fine merino wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Regular fit', 'Fine gauge, ribbed crew neck', 'Lightweight, approx. 260 g (size M)', 'Knitted in small batches in Latvia']::text[], 12900, '[{"name":"Pebble","hex":"#cdc8bd"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Baltic Blue","hex":"#5d7488"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-06.webp']::text[], false, false, true, 10);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Pebble', 'XS', 3, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Pebble', 'S', 1, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Pebble', 'M', 12, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Pebble', 'L', 13, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Pebble', 'XL', 2, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Charcoal', 'XS', 9, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Charcoal', 'S', 0, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Charcoal', 'M', 9, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Charcoal', 'L', 2, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Charcoal', 'XL', 3, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Baltic Blue', 'XS', 4, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Baltic Blue', 'S', 11, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Baltic Blue', 'M', 0, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Baltic Blue', 'L', 4, null),
  ((select id from public.products where slug = 'rits-merino-fine-knit'), 'Baltic Blue', 'XL', 0, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('dzintars-rib-crew', 'sweaters', 'Dzintars Rib Crew', 'A relaxed rib crew in amber, ecru and camel', 'Named for Baltic amber, Dzintars is a relaxed crewneck in a soft fisherman rib, knitted in three warm colours: amber, undyed ecru and camel. The rib gives it stretch and bounce, and the dropped shoulders make it easy to layer over a shirt.

The colours are dyed to sit well together, so they''re often bought in pairs.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Relaxed fit', 'Fisherman rib, ribbed crew neck', 'Mid-weight, approx. 540 g (size M)', 'Knitted in small batches in Latvia']::text[], 17900, '[{"name":"Amber","hex":"#c8922e"},{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Camel","hex":"#a87c55"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/sweater-11.webp', 'products/sweater-10.webp']::text[], true, true, true, 11);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Amber', 'XS', 4, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Amber', 'S', 8, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Amber', 'M', 3, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Amber', 'L', 6, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Amber', 'XL', 15, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Undyed Ecru', 'XS', 3, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Undyed Ecru', 'S', 5, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Undyed Ecru', 'M', 11, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Undyed Ecru', 'L', 0, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Undyed Ecru', 'XL', 5, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Camel', 'XS', 0, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Camel', 'S', 8, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Camel', 'M', 5, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Camel', 'L', 11, null),
  ((select id from public.products where slug = 'dzintars-rib-crew'), 'Camel', 'XL', 5, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('liepa-classic-cardigan', 'cardigans', 'Liepa Classic Cardigan', 'The buttoned cardigan, done properly', 'Liepa is our take on the cardigan everyone should own: a soft, slightly brushed grey melange with ribbed sleeves, a reinforced button band that won''t sag and dark tortoiseshell-effect buttons.

It''s the layer we reach for from October to April, over a shirt, a dress or another sweater.', 'Lambswool blend; tortoiseshell-effect buttons', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Regular fit', 'Button front, ribbed sleeves', 'Mid-weight, approx. 500 g (size M)', 'Knitted in small batches in Latvia']::text[], 17900, '[{"name":"Grey Melange","hex":"#a9a8a2"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Lingonberry","hex":"#8e2f36"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/cardigan-03.webp']::text[], true, false, true, 1);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Grey Melange', 'XS', 1, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Grey Melange', 'S', 4, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Grey Melange', 'M', 8, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Grey Melange', 'L', 6, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Grey Melange', 'XL', 5, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Oat', 'XS', 14, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Oat', 'S', 13, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Oat', 'M', 9, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Oat', 'L', 3, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Oat', 'XL', 7, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Charcoal', 'XS', 9, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Charcoal', 'S', 0, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Charcoal', 'M', 4, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Charcoal', 'L', 7, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Charcoal', 'XL', 14, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Lingonberry', 'XS', 0, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Lingonberry', 'S', 7, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Lingonberry', 'M', 15, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Lingonberry', 'L', 10, null),
  ((select id from public.products where slug = 'liepa-classic-cardigan'), 'Lingonberry', 'XL', 2, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('abele-openwork-cardigan', 'cardigans', 'Ābele Openwork Cardigan', 'A V-neck with an openwork leaf pattern', 'A soft V-neck cardigan with an openwork pattern of small leaves climbing up the body, like an apple tree coming into leaf. Ābele is knitted in a fine, slightly fuzzy wool in a deep jade green, with ribbed cuffs and hem.

Pretty enough for a summer wedding, warm enough for a northern one.', '100% merino wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Regular fit', 'Openwork leaf pattern, V-neck', 'Lightweight, approx. 320 g (size M)', 'Knitted in small batches in Latvia']::text[], 16900, '[{"name":"Jade","hex":"#3f8a6e"},{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Birch","hex":"#cfc6b6"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/cardigan-04.webp']::text[], false, false, true, 2);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Jade', 'XS', 9, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Jade', 'S', 9, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Jade', 'M', 8, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Jade', 'L', 13, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Jade', 'XL', 15, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Undyed Ecru', 'XS', 0, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Undyed Ecru', 'S', 6, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Undyed Ecru', 'M', 1, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Undyed Ecru', 'L', 2, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Undyed Ecru', 'XL', 5, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Birch', 'XS', 3, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Birch', 'S', 4, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Birch', 'M', 5, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Birch', 'L', 7, null),
  ((select id from public.products where slug = 'abele-openwork-cardigan'), 'Birch', 'XL', 10, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('vakars-cropped-cardigan', 'cardigans', 'Vakars Cropped Cardigan', 'Chunky rib, cropped, with big sleeves', 'A cropped cardigan in a chunky fisherman rib, with a deep V-neck, five dark buttons and generous balloon sleeves gathered into a ribbed cuff. Vakars sits at the waist, so it''s easy over dresses and high-waisted skirts.

Made for evenings by the sea when the wind picks up.', '100% lambswool; dark corozo buttons', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Cropped fit', 'Fisherman rib, five buttons, full sleeves', 'Mid-weight, approx. 520 g (size M)', 'Knitted in small batches in Latvia']::text[], 17500, '[{"name":"Frost Grey","hex":"#d6d3cc"},{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Heather Plum","hex":"#7a5a66"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/cardigan-05.webp']::text[], false, true, true, 3);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Frost Grey', 'XS', 4, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Frost Grey', 'S', 11, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Frost Grey', 'M', 7, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Frost Grey', 'L', 4, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Frost Grey', 'XL', 11, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Undyed Ecru', 'XS', 14, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Undyed Ecru', 'S', 8, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Undyed Ecru', 'M', 12, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Undyed Ecru', 'L', 8, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Undyed Ecru', 'XL', 5, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Heather Plum', 'XS', 15, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Heather Plum', 'S', 11, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Heather Plum', 'M', 4, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Heather Plum', 'L', 12, null),
  ((select id from public.products where slug = 'vakars-cropped-cardigan'), 'Heather Plum', 'XL', 15, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('egle-oversized-cardigan', 'cardigans', 'Egle Oversized Cardigan', 'An open, oversized rib cardigan', 'A long, loose cardigan in a chunky rib that''s made to be worn open and slipping off one shoulder. Egle has no buttons — just a wide ribbed front band that falls in soft folds — and sleeves long enough to pull over your hands.

The kind of cardigan that ends up being worn instead of a coat.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Oversized fit', 'Open front, wide ribbed band', 'Heavyweight, approx. 850 g (size M)', 'Knitted in small batches in Latvia']::text[], 22900, '[{"name":"Light Grey","hex":"#c9c7c2"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Juniper","hex":"#3f5245"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array['products/cardigan-06.webp']::text[], false, false, true, 4);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Light Grey', 'XS', 12, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Light Grey', 'S', 1, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Light Grey', 'M', 3, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Light Grey', 'L', 3, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Light Grey', 'XL', 7, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Oat', 'XS', 3, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Oat', 'S', 15, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Oat', 'M', 15, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Oat', 'L', 5, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Oat', 'XL', 13, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Juniper', 'XS', 1, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Juniper', 'S', 2, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Juniper', 'M', 12, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Juniper', 'L', 9, null),
  ((select id from public.products where slug = 'egle-oversized-cardigan'), 'Juniper', 'XL', 14, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('mezs-long-cardigan', 'cardigans', 'Mežs Long Cardigan', 'Knee-length, with a tie belt', 'Mežs is almost a coat. It falls just above the knee, has deep side pockets and a knitted belt you can tie or leave out. The double-knit front panels stay flat and smooth, while the sleeves are ribbed for a close cuff.

Made for forest walks, quiet Sunday mornings and everything between.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Relaxed, long fit', 'Removable tie belt, side pockets', 'Heavyweight, approx. 900 g (size M)', 'Knitted in small batches in Latvia']::text[], 22900, '[{"name":"Moss","hex":"#6b7358"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array[]::text[], false, false, false, 5);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Moss', 'XS', 13, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Moss', 'S', 0, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Moss', 'M', 2, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Moss', 'L', 12, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Moss', 'XL', 12, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Oat', 'XS', 2, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Oat', 'S', 15, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Oat', 'M', 10, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Oat', 'L', 0, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Oat', 'XL', 15, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Charcoal', 'XS', 13, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Charcoal', 'S', 10, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Charcoal', 'M', 6, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Charcoal', 'L', 3, null),
  ((select id from public.products where slug = 'mezs-long-cardigan'), 'Charcoal', 'XL', 6, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('vejs-zip-cardigan', 'cardigans', 'Vējš Zip Cardigan', 'A zip-through knit with a stand collar', 'Vējš (wind) is a sturdy, zip-through cardigan with a high stand collar and a two-way zip. The textured half-cardigan stitch makes it thick and springy without being heavy.

Our favourite for cycling, the seaside and anything outdoors.', '100% lambswool; two-way metal zip', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Regular fit', 'Two-way zip, stand collar', 'Mid-weight, approx. 640 g (size M)', 'Knitted in small batches in Latvia']::text[], 19900, '[{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Night Blue","hex":"#2f3a4d"},{"name":"Rye","hex":"#b08a5a"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array[]::text[], false, false, false, 6);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Charcoal', 'XS', 7, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Charcoal', 'S', 11, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Charcoal', 'M', 0, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Charcoal', 'L', 11, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Charcoal', 'XL', 0, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Night Blue', 'XS', 4, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Night Blue', 'S', 4, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Night Blue', 'M', 15, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Night Blue', 'L', 4, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Night Blue', 'XL', 2, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Rye', 'XS', 5, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Rye', 'S', 0, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Rye', 'M', 11, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Rye', 'L', 2, null),
  ((select id from public.products where slug = 'vejs-zip-cardigan'), 'Rye', 'XL', 3, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('sniegs-mohair-cardigan', 'cardigans', 'Sniegs Mohair Cardigan', 'An airy mohair cardigan with a cloud-soft halo', 'Sniegs is loose, light and a little bit dreamy. Kid mohair and merino are knitted together at an open gauge for a cardigan that floats rather than clings, with oversized buttons to match.

Throw it over everything.', '70% kid mohair, 30% merino wool; corozo buttons', array['Hand wash cold (max 30 °C) with a wool detergent', 'Dry flat and brush lightly once dry to lift the halo', 'Fold, never hang', 'Store with cedar or lavender between seasons']::text[], array['Oversized fit', 'Open gauge, five large buttons', 'Lightweight, approx. 300 g (size M)', 'Knitted in small batches in Latvia']::text[], 18900, '[{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Fog Grey","hex":"#b9b8b0"},{"name":"Honey","hex":"#c99a4b"}]'::jsonb, array['XS', 'S', 'M', 'L', 'XL']::text[], array[]::text[], false, false, false, 7);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Undyed Ecru', 'XS', 10, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Undyed Ecru', 'S', 14, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Undyed Ecru', 'M', 6, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Undyed Ecru', 'L', 10, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Undyed Ecru', 'XL', 5, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Fog Grey', 'XS', 5, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Fog Grey', 'S', 1, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Fog Grey', 'M', 6, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Fog Grey', 'L', 0, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Fog Grey', 'XL', 3, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Honey', 'XS', 12, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Honey', 'S', 5, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Honey', 'M', 6, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Honey', 'L', 2, null),
  ((select id from public.products where slug = 'sniegs-mohair-cardigan'), 'Honey', 'XL', 7, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('kapa-rib-beanie', 'hats', 'Kāpa Rib Beanie', 'Classic ribbed beanie with a deep turn-up', 'A simple ribbed beanie in soft lambswool. The long body folds into a double-layer turn-up over the ears, and the crown is shaped so it sits softly rather than peaks.

The hat we give to friends — usually in rust.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['One size, fits most adults', 'Double-layer turn-up', 'Knitted in small batches in Latvia']::text[], 4500, '[{"name":"Rust","hex":"#a45a3a"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Moss","hex":"#6b7358"}]'::jsonb, array['One size']::text[], array['products/hat-03.webp']::text[], false, false, true, 1);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'kapa-rib-beanie'), 'Rust', 'One size', 3, null),
  ((select id from public.products where slug = 'kapa-rib-beanie'), 'Oat', 'One size', 2, null),
  ((select id from public.products where slug = 'kapa-rib-beanie'), 'Charcoal', 'One size', 5, null),
  ((select id from public.products where slug = 'kapa-rib-beanie'), 'Moss', 'One size', 5, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('priede-turn-up-beanie', 'hats', 'Priede Turn-Up Beanie', 'A soft caramel beanie with a wide cuff', 'A close-fitting beanie in a fine rib, with a wide turn-up that sits just above the eyebrows. Priede is knitted in a soft, slightly brushed wool that doesn''t itch at the forehead, in a warm caramel that suits almost everyone.

Fold it once, pull it down, done.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['One size, fits most adults', 'Fine rib, wide turn-up', 'Knitted in small batches in Latvia']::text[], 4900, '[{"name":"Caramel","hex":"#b07a4c"},{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Juniper","hex":"#3f5245"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['One size']::text[], array['products/hat-02.webp', 'products/hat-05.webp']::text[], true, false, true, 2);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'priede-turn-up-beanie'), 'Caramel', 'One size', 11, null),
  ((select id from public.products where slug = 'priede-turn-up-beanie'), 'Undyed Ecru', 'One size', 15, null),
  ((select id from public.products where slug = 'priede-turn-up-beanie'), 'Juniper', 'One size', 1, null),
  ((select id from public.products where slug = 'priede-turn-up-beanie'), 'Charcoal', 'One size', 4, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('egle-slouch-beanie', 'hats', 'Egle Slouch Beanie', 'Chunky and slouchy, in pine green', 'A chunky slouch beanie with deep ridges knitted in bands from brim to crown, so it gathers softly at the back of the head. Egle is thick and warm, in a dark pine green that looks good against every colour of hair.

For windy hilltops and long walks home.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['One size, fits most adults', 'Slouchy fit, ridged bands', 'Knitted in small batches in Latvia']::text[], 5500, '[{"name":"Pine Green","hex":"#2f4a36"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['One size']::text[], array['products/hat-01.webp']::text[], false, false, true, 3);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'egle-slouch-beanie'), 'Pine Green', 'One size', 7, null),
  ((select id from public.products where slug = 'egle-slouch-beanie'), 'Oat', 'One size', 2, null),
  ((select id from public.products where slug = 'egle-slouch-beanie'), 'Charcoal', 'One size', 13, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('jura-merino-watch-cap', 'hats', 'Jūra Merino Watch Cap', 'Fine merino cap for milder days', 'A fine, close-fitting watch cap in extra-fine merino. Jūra is thin enough to wear for a run or under a hood, and breathes well on autumn days that can''t decide what they are.

No itch, no fuss.', '100% extra-fine merino wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['One size, fits most adults', 'Fine rib, close fit', 'Knitted in small batches in Latvia']::text[], 3900, '[{"name":"Night Blue","hex":"#2f3a4d"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Sea Glass","hex":"#a9b8b0"},{"name":"Lingonberry","hex":"#8e2f36"}]'::jsonb, array['One size']::text[], array[]::text[], false, false, false, 4);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'jura-merino-watch-cap'), 'Night Blue', 'One size', 9, null),
  ((select id from public.products where slug = 'jura-merino-watch-cap'), 'Charcoal', 'One size', 6, null),
  ((select id from public.products where slug = 'jura-merino-watch-cap'), 'Sea Glass', 'One size', 15, null),
  ((select id from public.products where slug = 'jura-merino-watch-cap'), 'Lingonberry', 'One size', 12, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('salna-star-hat', 'hats', 'Salna Star Hat', 'Colourwork hat with a wool pompom', 'A star pattern borrowed from old Latvian mittens, knitted around a warm, double-layered hat and finished with a big wool pompom. Because it''s stranded in two colours, it''s twice as warm as a plain knit.

Lined with a fine merino band at the forehead for comfort.', '100% lambswool; merino inner band', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['One size, fits most adults', 'Two-colour stranded knit, pompom', 'Knitted in small batches in Latvia']::text[], 5900, '[{"name":"Ecru / Night Blue","hex":"#ede6d6"},{"name":"Charcoal / Oat","hex":"#3e3d3b"}]'::jsonb, array['One size']::text[], array[]::text[], false, false, false, 5);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'salna-star-hat'), 'Ecru / Night Blue', 'One size', 5, null),
  ((select id from public.products where slug = 'salna-star-hat'), 'Charcoal / Oat', 'One size', 0, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('puce-earflap-hat', 'hats', 'Pūce Earflap Hat', 'Earflaps and braided ties for real winter', 'For the coldest days of the year. Pūce has knitted earflaps with braided ties, a doubled brim and a wool pompom on top. Knitted in a thick lambswool that shrugs off snow.

Named after the owl, who is always wise enough to stay warm.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['One size, fits most adults', 'Earflaps with braided ties', 'Knitted in small batches in Latvia']::text[], 6500, '[{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Rust","hex":"#a45a3a"}]'::jsonb, array['One size']::text[], array[]::text[], false, false, false, 6);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'puce-earflap-hat'), 'Charcoal', 'One size', 2, null),
  ((select id from public.products where slug = 'puce-earflap-hat'), 'Oat', 'One size', 2, null),
  ((select id from public.products where slug = 'puce-earflap-hat'), 'Rust', 'One size', 6, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('egle-chunky-wrap', 'scarves', 'Egle Chunky Wrap', 'An oversized wrap that doubles as a shawl', 'Wide enough to wear over the shoulders as a shawl, long enough to wrap twice as a scarf. Egle is knitted in a chunky oat wool with deep horizontal ridges that give it an almost woven look.

For cold trains, big coats and sitting outside long after the sun has gone.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Approx. 60 × 210 cm', 'Chunky ridged texture', 'Knitted in small batches in Latvia']::text[], 12500, '[{"name":"Oat","hex":"#d9ccb4"},{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Juniper","hex":"#3f5245"}]'::jsonb, array['One size']::text[], array['products/scarf-03.webp']::text[], true, false, true, 1);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'egle-chunky-wrap'), 'Oat', 'One size', 15, null),
  ((select id from public.products where slug = 'egle-chunky-wrap'), 'Undyed Ecru', 'One size', 12, null),
  ((select id from public.products where slug = 'egle-chunky-wrap'), 'Juniper', 'One size', 12, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('migla-mohair-scarf', 'scarves', 'Migla Mohair Scarf', 'A cloud of brushed mohair', 'A wide, feather-light scarf in brushed mohair and merino, knitted in a soft garter stitch. It bunches beautifully at the neck and weighs almost nothing in a bag.

The softest thing we make, and the one most often bought as a gift.', '70% kid mohair, 30% merino wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Dry flat and brush lightly once dry to lift the halo', 'Fold, never hang', 'Store with cedar or lavender between seasons']::text[], array['Approx. 40 × 190 cm', 'Airy garter stitch', 'Knitted in small batches in Latvia']::text[], 8900, '[{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Fog Grey","hex":"#b9b8b0"},{"name":"Honey","hex":"#c99a4b"}]'::jsonb, array['One size']::text[], array['products/scarf-05.webp']::text[], false, false, true, 2);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'migla-mohair-scarf'), 'Undyed Ecru', 'One size', 13, null),
  ((select id from public.products where slug = 'migla-mohair-scarf'), 'Fog Grey', 'One size', 9, null),
  ((select id from public.products where slug = 'migla-mohair-scarf'), 'Honey', 'One size', 15, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('kapa-long-scarf', 'scarves', 'Kāpa Long Scarf', 'A long, soft scarf in forest green', 'A long, generous scarf in soft lambswool, knitted to a full 220 cm so it can go round twice and still hang to the waist. Kāpa is plain and dense, in a dark forest green that goes with every winter coat.

Simple and warm — the scarf that stays by the door.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Approx. 35 × 220 cm', 'Smooth stocking stitch', 'Knitted in small batches in Latvia']::text[], 8500, '[{"name":"Forest Green","hex":"#3f5a3c"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['One size']::text[], array['products/scarf-02.webp']::text[], false, false, true, 3);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'kapa-long-scarf'), 'Forest Green', 'One size', 11, null),
  ((select id from public.products where slug = 'kapa-long-scarf'), 'Oat', 'One size', 7, null),
  ((select id from public.products where slug = 'kapa-long-scarf'), 'Charcoal', 'One size', 0, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('virsi-garter-scarf', 'scarves', 'Virši Garter Scarf', 'Garter stitch in heather lilac', 'Virši means heather, and this scarf has its colour: a soft, dusty lilac with flecks of grey. It''s knitted in a squishy garter stitch that looks the same on both sides and never curls at the edges.

A gentle colour for grey days.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Approx. 30 × 190 cm', 'Reversible garter stitch', 'Knitted in small batches in Latvia']::text[], 7900, '[{"name":"Heather Lilac","hex":"#9b8a96"},{"name":"Fog Grey","hex":"#b9b8b0"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['One size']::text[], array['products/scarf-04.webp']::text[], false, true, true, 4);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'virsi-garter-scarf'), 'Heather Lilac', 'One size', 3, null),
  ((select id from public.products where slug = 'virsi-garter-scarf'), 'Fog Grey', 'One size', 0, null),
  ((select id from public.products where slug = 'virsi-garter-scarf'), 'Oat', 'One size', 1, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('sarts-chunky-scarf', 'scarves', 'Sārts Chunky Scarf', 'A thick seed-stitch scarf in dusty rose', 'A thick, cosy scarf in a chunky seed stitch, knitted from a plump wool in a soft dusty rose. The bobbly texture traps warmth and holds its shape however you wrap it.

Sārts means rosy — which is what your cheeks will be after a walk in the frost.', '100% Nordic wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Approx. 28 × 180 cm', 'Chunky seed stitch', 'Knitted in small batches in Latvia']::text[], 9500, '[{"name":"Dusty Rose","hex":"#c9a79a"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['One size']::text[], array['products/scarf-01.webp']::text[], false, false, true, 5);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'sarts-chunky-scarf'), 'Dusty Rose', 'One size', 15, null),
  ((select id from public.products where slug = 'sarts-chunky-scarf'), 'Oat', 'One size', 7, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('lietus-woven-scarf', 'scarves', 'Lietus Woven Scarf', 'A soft woven wool scarf with fringed ends', 'A wide, soft scarf woven from brushed wool and finished with a long fringe at each end. Lietus (rain) is lighter than our knitted scarves and drapes beautifully — wrap it loosely or wear it long over a dark coat.

It softens noticeably after the first few wears.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Dry flat', 'Comb the fringe gently once dry']::text[], array['Approx. 50 × 190 cm plus fringe', 'Woven, brushed finish', 'Made in small batches in Latvia']::text[], 8900, '[{"name":"Grass Green","hex":"#3e7b3a"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['One size']::text[], array['products/scarf-06.webp']::text[], false, false, true, 6);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'lietus-woven-scarf'), 'Grass Green', 'One size', 9, null),
  ((select id from public.products where slug = 'lietus-woven-scarf'), 'Charcoal', 'One size', 1, null),
  ((select id from public.products where slug = 'lietus-woven-scarf'), 'Oat', 'One size', 3, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('sniegs-snowflake-mittens', 'mittens', 'Sniegs Snowflake Mittens', 'Chunky snowflake mittens in red and ecru', 'Big, warm mittens with a band of white snowflakes on a red ground, bordered with stripes and small diamonds, and a long ribbed ecru cuff to tuck into your sleeves. Sniegs (snow) is knitted in a thick wool, stranded in two colours for double warmth.

Made for snowball fights and mugs of something hot.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Chunky stranded colourwork', 'Long ribbed cuff', 'Knitted in small batches in Latvia']::text[], 4900, '[{"name":"Red / Ecru","hex":"#b3232a"}]'::jsonb, array['S/M', 'M/L']::text[], array['products/mittens-02.webp']::text[], true, true, true, 1);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'sniegs-snowflake-mittens'), 'Red / Ecru', 'S/M', 6, null),
  ((select id from public.products where slug = 'sniegs-snowflake-mittens'), 'Red / Ecru', 'M/L', 11, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('plava-flower-mittens', 'mittens', 'Pļava Flower Mittens', 'Daisies on dark brown, with a green cuff', 'Pļava (meadow) mittens carry a pattern of white daisies with golden centres on a dark bark-brown ground, finished with a green ribbed cuff. Stranded colourwork makes the fabric dense and wind-resistant, and every pair is a little different where the flowers meet the thumb.

A summer meadow for the middle of winter.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Fine stranded colourwork', 'Ribbed cuff in a contrast colour', 'Knitted in small batches in Latvia']::text[], 5800, '[{"name":"Bark / Ecru","hex":"#4e4038"}]'::jsonb, array['S/M', 'M/L']::text[], array['products/mittens-03.webp']::text[], false, true, true, 2);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'plava-flower-mittens'), 'Bark / Ecru', 'S/M', 7, null),
  ((select id from public.products where slug = 'plava-flower-mittens'), 'Bark / Ecru', 'M/L', 14, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('migla-cable-mittens', 'mittens', 'Migla Cable Mittens', 'Cables and seed stitch in stone grey', 'Soft grey mittens with a single leafy cable framed by seed stitch, and a neat ribbed cuff. Migla (fog) is knitted in a fine lambswool that''s warm without being bulky, so you can still hold keys and tickets.

Quiet mittens for every day.', '100% lambswool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Do not wring — press out water in a towel', 'Dry flat, gently reshaped, away from direct heat', 'Air between wears; remove pilling with a wool comb']::text[], array['Cable and seed stitch', 'Ribbed cuff', 'Knitted in small batches in Latvia']::text[], 4500, '[{"name":"Stone Grey","hex":"#6f6a64"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['S/M', 'M/L']::text[], array['products/mittens-01.webp']::text[], false, false, true, 3);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'migla-cable-mittens'), 'Stone Grey', 'S/M', 2, null),
  ((select id from public.products where slug = 'migla-cable-mittens'), 'Stone Grey', 'M/L', 0, null),
  ((select id from public.products where slug = 'migla-cable-mittens'), 'Oat', 'S/M', 9, null),
  ((select id from public.products where slug = 'migla-cable-mittens'), 'Oat', 'M/L', 7, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('ezers-rib-socks', 'socks', 'Ezers Rib Socks', 'Long rib socks in cranberry, sky and navy', 'Our everyday sock: a long, soft rib that reaches to mid-calf and stays up without pinching. Ezers comes in cranberry red, sky blue and navy, and is knitted from wool with a little polyamide for strength at the heel and toe.

Warm in winter boots, breathable in trainers.', '75% merino wool, 25% polyamide', array['Machine wash on the wool cycle at 30 °C, inside out', 'Do not tumble dry', 'Dry flat or over a rail']::text[], array['Mid-calf length', 'Rib throughout, reinforced heel and toe', 'Knitted in small batches in Latvia']::text[], 2400, '[{"name":"Cranberry","hex":"#b3232a"},{"name":"Sky Blue","hex":"#9db8e0"},{"name":"Navy","hex":"#2e3450"}]'::jsonb, array['36–38', '39–41', '42–44', '45–47']::text[], array['products/socks-03.webp', 'products/socks-02.webp', 'products/socks-04.webp']::text[], true, false, true, 1);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Cranberry', '36–38', 12, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Cranberry', '39–41', 7, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Cranberry', '42–44', 0, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Cranberry', '45–47', 2, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Sky Blue', '36–38', 4, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Sky Blue', '39–41', 2, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Sky Blue', '42–44', 9, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Sky Blue', '45–47', 6, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Navy', '36–38', 0, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Navy', '39–41', 15, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Navy', '42–44', 3, null),
  ((select id from public.products where slug = 'ezers-rib-socks'), 'Navy', '45–47', 12, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('meness-lace-cable-socks', 'socks', 'Mēness Lace-Cable Socks', 'Lace and cables in stone grey', 'Fine socks with a pattern of lace and small cables running from cuff to toe, in a soft stone grey. Mēness (moon) socks are thin enough for shoes and pretty enough to show off with a cropped trouser.

The pair people ask about.', '75% merino wool, 25% polyamide', array['Machine wash on the wool cycle at 30 °C, inside out', 'Do not tumble dry', 'Dry flat or over a rail']::text[], array['Mid-calf length', 'Lace-cable pattern', 'Knitted in small batches in Latvia']::text[], 3400, '[{"name":"Stone Grey","hex":"#6f6a64"},{"name":"Undyed Ecru","hex":"#ede6d6"}]'::jsonb, array['36–38', '39–41', '42–44', '45–47']::text[], array['products/socks-01.webp']::text[], false, false, true, 2);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Stone Grey', '36–38', 6, null),
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Stone Grey', '39–41', 11, null),
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Stone Grey', '42–44', 14, null),
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Stone Grey', '45–47', 10, null),
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Undyed Ecru', '36–38', 5, null),
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Undyed Ecru', '39–41', 5, null),
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Undyed Ecru', '42–44', 15, null),
  ((select id from public.products where slug = 'meness-lace-cable-socks'), 'Undyed Ecru', '45–47', 13, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('salna-pattern-socks', 'socks', 'Salna Pattern Socks', 'Snowflake pattern with bright blue heels', 'Short, patterned socks with blue snowflakes and small diamonds on an ecru ground, and bright cornflower-blue cuffs, heels and toes. Stranded colourwork doubles the thickness, so these are properly warm — the pair for a cold floor on a winter morning.

They make a very good present.', '80% wool, 20% polyamide', array['Machine wash on the wool cycle at 30 °C, inside out', 'Do not tumble dry', 'Dry flat or over a rail']::text[], array['Ankle length', 'Two-colour stranded pattern, contrast heel and toe', 'Knitted in small batches in Latvia']::text[], 3200, '[{"name":"Ecru / Cornflower","hex":"#ede6d6"}]'::jsonb, array['36–38', '39–41', '42–44', '45–47']::text[], array['products/socks-05.webp']::text[], false, true, true, 3);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'salna-pattern-socks'), 'Ecru / Cornflower', '36–38', 5, null),
  ((select id from public.products where slug = 'salna-pattern-socks'), 'Ecru / Cornflower', '39–41', 11, null),
  ((select id from public.products where slug = 'salna-pattern-socks'), 'Ecru / Cornflower', '42–44', 5, null),
  ((select id from public.products where slug = 'salna-pattern-socks'), 'Ecru / Cornflower', '45–47', 0, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('upe-everyday-wool-socks', 'socks', 'Upe Everyday Wool Socks', 'Everyday wool socks, reinforced where it counts', 'Upe is knitted from wool with a little nylon for strength, reinforced at the heel and toe, and finished with a soft rib cuff that stays up without pinching.

Warm in winter boots, breathable in trainers.', '80% wool, 20% polyamide', array['Machine wash on the wool cycle at 30 °C, inside out', 'Do not tumble dry', 'Dry flat or over a rail']::text[], array['Mid-calf length', 'Reinforced heel and toe', 'Knitted in small batches in Latvia']::text[], 2200, '[{"name":"Moss","hex":"#6b7358"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['36–38', '39–41', '42–44', '45–47']::text[], array[]::text[], false, false, false, 4);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Moss', '36–38', 13, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Moss', '39–41', 13, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Moss', '42–44', 13, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Moss', '45–47', 5, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Oat', '36–38', 3, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Oat', '39–41', 8, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Oat', '42–44', 6, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Oat', '45–47', 3, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Charcoal', '36–38', 8, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Charcoal', '39–41', 0, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Charcoal', '42–44', 15, null),
  ((select id from public.products where slug = 'upe-everyday-wool-socks'), 'Charcoal', '45–47', 14, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('mezs-boot-socks', 'socks', 'Mežs Boot Socks', 'Thick cushioned socks for walking boots', 'Thick, cushioned boot socks with a terry-knit sole for long walks and wet forest paths. The leg is ribbed and long enough to fold over the top of a boot.

Wool stays warm even when damp, which is exactly the point.', '75% wool, 25% polyamide', array['Machine wash on the wool cycle at 30 °C, inside out', 'Do not tumble dry', 'Dry flat or over a rail']::text[], array['Knee-high, fold-over cuff', 'Cushioned terry sole', 'Knitted in small batches in Latvia']::text[], 2900, '[{"name":"Moss","hex":"#6b7358"},{"name":"Charcoal","hex":"#3e3d3b"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['36–38', '39–41', '42–44', '45–47']::text[], array[]::text[], false, false, false, 5);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Moss', '36–38', 0, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Moss', '39–41', 7, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Moss', '42–44', 11, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Moss', '45–47', 14, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Charcoal', '36–38', 9, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Charcoal', '39–41', 4, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Charcoal', '42–44', 2, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Charcoal', '45–47', 1, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Oat', '36–38', 2, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Oat', '39–41', 11, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Oat', '42–44', 1, null),
  ((select id from public.products where slug = 'mezs-boot-socks'), 'Oat', '45–47', 0, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('sniegs-alpaca-bed-socks', 'socks', 'Sniegs Alpaca Bed Socks', 'Soft alpaca socks for cold nights', 'Loose, very soft bed socks in brushed alpaca. They have a relaxed cuff that won''t leave marks and a slightly fuzzy finish that feels lovely on bare skin.

For cold nights and slow mornings.', '60% baby alpaca, 40% wool', array['Hand wash cold (max 30 °C) with a wool detergent', 'Dry flat', 'Do not tumble dry']::text[], array['Ankle length, relaxed cuff', 'Brushed finish', 'Knitted in small batches in Latvia']::text[], 2800, '[{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Honey","hex":"#c99a4b"},{"name":"Fog Grey","hex":"#b9b8b0"}]'::jsonb, array['36–38', '39–41', '42–44', '45–47']::text[], array[]::text[], false, false, false, 6);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Undyed Ecru', '36–38', 14, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Undyed Ecru', '39–41', 14, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Undyed Ecru', '42–44', 7, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Undyed Ecru', '45–47', 0, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Honey', '36–38', 2, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Honey', '39–41', 10, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Honey', '42–44', 1, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Honey', '45–47', 0, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Fog Grey', '36–38', 6, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Fog Grey', '39–41', 11, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Fog Grey', '42–44', 0, null),
  ((select id from public.products where slug = 'sniegs-alpaca-bed-socks'), 'Fog Grey', '45–47', 8, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('salna-diamond-throw', 'blankets', 'Salna Diamond Throw', 'Woven diamonds in rust, mustard and ochre', 'A soft woven wool throw with a pattern of small diamonds, like frost on a window. Salna comes in rust with ecru diamonds, mustard and ochre — warm autumn colours that look even better stacked together.

Heavy enough for a bed in winter, and made to be handed down.', '100% lambswool', array['Air outside regularly — wool rarely needs washing', 'Spot clean with cold water where possible', 'When needed, hand wash cold or dry clean', 'Dry flat; do not tumble dry']::text[], array['Woven diamond pattern', 'Approx. 1.4 kg (throw size)', 'Made in small batches in Latvia']::text[], 18900, '[{"name":"Rust / Ecru","hex":"#a45a3a"},{"name":"Mustard","hex":"#c9a032"},{"name":"Ochre","hex":"#b0782a"}]'::jsonb, array['Throw 130 × 170 cm', 'Large 150 × 200 cm']::text[], array['products/blanket-01.webp']::text[], true, false, true, 1);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'salna-diamond-throw'), 'Rust / Ecru', 'Throw 130 × 170 cm', 8, null),
  ((select id from public.products where slug = 'salna-diamond-throw'), 'Rust / Ecru', 'Large 150 × 200 cm', 11, 23900),
  ((select id from public.products where slug = 'salna-diamond-throw'), 'Mustard', 'Throw 130 × 170 cm', 0, null),
  ((select id from public.products where slug = 'salna-diamond-throw'), 'Mustard', 'Large 150 × 200 cm', 10, 23900),
  ((select id from public.products where slug = 'salna-diamond-throw'), 'Ochre', 'Throw 130 × 170 cm', 0, null),
  ((select id from public.products where slug = 'salna-diamond-throw'), 'Ochre', 'Large 150 × 200 cm', 12, 23900);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('jura-fringed-throw', 'blankets', 'Jūra Fringed Throw', 'Soft blue woven wool with a long fringe', 'A light, soft throw woven in a blue-grey wool with a subtle texture, finished with a long fringe on every edge. Jūra (sea) adds warmth without weight — fold it at the foot of the bed or pull it over your shoulders on a cool evening.

The colour shifts from grey to blue with the light.', '100% lambswool', array['Air outside regularly — wool rarely needs washing', 'Spot clean with cold water where possible', 'When needed, hand wash cold or dry clean', 'Dry flat; do not tumble dry']::text[], array['Woven, fringed edges', 'Approx. 0.9 kg', 'Made in small batches in Latvia']::text[], 16900, '[{"name":"Baltic Blue","hex":"#5d7488"},{"name":"Fog Grey","hex":"#b9b8b0"}]'::jsonb, array['Throw 130 × 170 cm']::text[], array['products/blanket-02.webp']::text[], false, true, true, 2);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'jura-fringed-throw'), 'Baltic Blue', 'Throw 130 × 170 cm', 11, null),
  ((select id from public.products where slug = 'jura-fringed-throw'), 'Fog Grey', 'Throw 130 × 170 cm', 7, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('mezs-herringbone-throw', 'blankets', 'Mežs Herringbone Throw', 'Graphite herringbone with a knotted fringe', 'A classic herringbone and diamond twill in graphite and pale grey, woven from a sturdy wool and finished with a fringe at both ends. Mežs is the throw for the reading chair and the end of the sofa — the one you pull over your feet without thinking.

It only gets softer with use.', '100% lambswool', array['Air outside regularly — wool rarely needs washing', 'Spot clean with cold water where possible', 'When needed, hand wash cold or dry clean', 'Dry flat; do not tumble dry']::text[], array['Woven herringbone twill, fringed ends', 'Approx. 1.3 kg', 'Made in small batches in Latvia']::text[], 17900, '[{"name":"Graphite","hex":"#5d5c58"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['Throw 130 × 170 cm']::text[], array['products/blanket-03.webp']::text[], false, false, true, 3);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'mezs-herringbone-throw'), 'Graphite', 'Throw 130 × 170 cm', 15, null),
  ((select id from public.products where slug = 'mezs-herringbone-throw'), 'Oat', 'Throw 130 × 170 cm', 0, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('priede-chunky-knit-throw', 'blankets', 'Priede Chunky Knit Throw', 'Giant loops of pine-green merino', 'A statement blanket knitted in giant loops of soft, unspun merino, in a deep pine green. Priede is heavy, squishy and wonderfully warm — lay it over the bed or across the sofa and it becomes the most-touched thing in the room.

Each one is knitted loop by loop, so no two are quite the same.', '100% merino wool (unspun)', array['Spot clean only, with cold water and a little wool detergent', 'Do not machine wash or soak — the loops will felt', 'Shake out and air regularly; lay flat to store']::text[], array['Chunky knitted loops', 'Approx. 2.5 kg', 'Knitted in small batches in Latvia']::text[], 24900, '[{"name":"Pine Green","hex":"#2f4a36"},{"name":"Oat","hex":"#d9ccb4"},{"name":"Charcoal","hex":"#3e3d3b"}]'::jsonb, array['Throw 120 × 150 cm', 'Large 150 × 200 cm']::text[], array['products/blanket-04.webp']::text[], false, false, true, 4);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'priede-chunky-knit-throw'), 'Pine Green', 'Throw 120 × 150 cm', 5, null),
  ((select id from public.products where slug = 'priede-chunky-knit-throw'), 'Pine Green', 'Large 150 × 200 cm', 8, 32900),
  ((select id from public.products where slug = 'priede-chunky-knit-throw'), 'Oat', 'Throw 120 × 150 cm', 11, null),
  ((select id from public.products where slug = 'priede-chunky-knit-throw'), 'Oat', 'Large 150 × 200 cm', 7, 32900),
  ((select id from public.products where slug = 'priede-chunky-knit-throw'), 'Charcoal', 'Throw 120 × 150 cm', 13, null),
  ((select id from public.products where slug = 'priede-chunky-knit-throw'), 'Charcoal', 'Large 150 × 200 cm', 6, 32900);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('kapa-knitted-throw', 'blankets', 'Kāpa Knitted Throw', 'A fine-knit grey throw for every day', 'A simple, fine-knit throw in grey melange lambswool with a neat edge. Kāpa is light enough to leave on the sofa all year and fold into a neat square when guests come.

Our most practical blanket.', '100% lambswool', array['Air outside regularly — wool rarely needs washing', 'Spot clean with cold water where possible', 'When needed, hand wash cold or dry clean', 'Dry flat; do not tumble dry']::text[], array['Fine knit with neat edges', 'Approx. 1.1 kg', 'Knitted in small batches in Latvia']::text[], 14900, '[{"name":"Grey Melange","hex":"#a9a8a2"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['Throw 130 × 170 cm']::text[], array['products/blanket-05.webp']::text[], false, false, true, 5);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'kapa-knitted-throw'), 'Grey Melange', 'Throw 130 × 170 cm', 15, null),
  ((select id from public.products where slug = 'kapa-knitted-throw'), 'Oat', 'Throw 130 × 170 cm', 2, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('rits-merino-baby-blanket', 'blankets', 'Rīts Merino Baby Blanket', 'Soft merino for the smallest ones', 'A small, soft blanket in extra-fine merino, knitted in a gentle seed stitch with a garter border. Rīts is breathable, naturally temperature-regulating and gentle on new skin.

Often bought as a welcome gift — and usually kept long after it''s outgrown.', '100% extra-fine merino wool', array['Machine wash on the wool cycle at 30 °C', 'Dry flat', 'Do not tumble dry']::text[], array['Approx. 80 × 100 cm', 'Seed stitch with garter border', 'Knitted in small batches in Latvia']::text[], 9500, '[{"name":"Undyed Ecru","hex":"#ede6d6"},{"name":"Sea Glass","hex":"#a9b8b0"},{"name":"Oat","hex":"#d9ccb4"}]'::jsonb, array['One size']::text[], array[]::text[], false, false, false, 6);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'rits-merino-baby-blanket'), 'Undyed Ecru', 'One size', 10, null),
  ((select id from public.products where slug = 'rits-merino-baby-blanket'), 'Sea Glass', 'One size', 11, null),
  ((select id from public.products where slug = 'rits-merino-baby-blanket'), 'Oat', 'One size', 2, null);

insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values ('gauja-striped-picnic-blanket', 'blankets', 'Gauja Striped Picnic Blanket', 'Wide stripes for grass, sand and sofa', 'A sturdy, tightly knitted blanket in wide stripes, made for picnics by the river and cool evenings on the beach. Gauja is dense enough to sit on and washes well.

Comes rolled with a cotton carry strap.', '100% lambswool; cotton carry strap', array['Air outside regularly — wool rarely needs washing', 'Spot clean with cold water where possible', 'When needed, hand wash cold or dry clean', 'Dry flat; do not tumble dry']::text[], array['Dense knit, wide stripes', 'Approx. 1.6 kg, with carry strap', 'Knitted in small batches in Latvia']::text[], 18900, '[{"name":"Oat / Rust","hex":"#d9ccb4"},{"name":"Baltic / Ecru","hex":"#5d7488"}]'::jsonb, array['Throw 130 × 170 cm']::text[], array[]::text[], false, false, false, 7);
insert into public.product_variants (product_id, colour, size, stock, price_cents) values
  ((select id from public.products where slug = 'gauja-striped-picnic-blanket'), 'Oat / Rust', 'Throw 130 × 170 cm', 8, null),
  ((select id from public.products where slug = 'gauja-striped-picnic-blanket'), 'Baltic / Ecru', 'Throw 130 × 170 cm', 2, null);

commit;
