// Generates supabase/seed.sql from scripts/catalogue.mjs.
// Usage: node scripts/build-seed.mjs
import { writeFileSync } from "node:fs"
import { categories, products } from "./catalogue.mjs"

const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const arr = (xs) => `array[${xs.map(q).join(", ")}]::text[]`

// Deterministic pseudo-random stock so the seed is stable between runs.
let seed = 20260930
const rand = () => {
  seed = (seed * 1103515245 + 12345) % 2147483648
  return seed / 2147483648
}
const stockFor = () => {
  const r = rand()
  if (r < 0.1) return 0 // some variants sold out, as in a real small-batch shop
  if (r < 0.3) return 1 + Math.floor(rand() * 3) // low stock
  return 4 + Math.floor(rand() * 12)
}

const lines = [
  "-- Generated by scripts/build-seed.mjs — sample Nordaloom catalogue.",
  "-- Re-running replaces the catalogue (and any carts referencing it).",
  "begin;",
  "delete from public.products;",
  "delete from public.categories;",
  "",
]

categories.forEach((c, i) => {
  lines.push(
    `insert into public.categories (slug, name, tagline, description, image, sort_order) values (${q(c.slug)}, ${q(c.name)}, ${q(c.tagline)}, ${q(c.description)}, ${c.image ? q(c.image) : "null"}, ${i + 1});`,
  )
})
lines.push("")

const perCategory = {}
for (const p of products) {
  perCategory[p.category] = (perCategory[p.category] ?? 0) + 1
  lines.push(
    `insert into public.products (slug, category_slug, name, short_description, description, materials, care, details, price_cents, colours, sizes, images, is_featured, is_new, is_published, sort_order) values (` +
      [
        q(p.slug),
        q(p.category),
        q(p.name),
        q(p.short),
        q(p.description),
        q(p.materials),
        arr(p.care),
        arr(p.details),
        Math.round(p.price * 100),
        `${q(JSON.stringify(p.colours))}::jsonb`,
        arr(p.sizes),
        arr(p.images ?? []),
        p.featured ? "true" : "false",
        p.isNew ? "true" : "false",
        p.published === false ? "false" : "true",
        perCategory[p.category],
      ].join(", ") +
      `);`,
  )
  const values = []
  for (const colour of p.colours) {
    for (const size of p.sizes) {
      const override = p.sizePrices?.[size]
      values.push(
        `((select id from public.products where slug = ${q(p.slug)}), ${q(colour.name)}, ${q(size)}, ${stockFor()}, ${override ? Math.round(override * 100) : "null"})`,
      )
    }
  }
  lines.push(
    `insert into public.product_variants (product_id, colour, size, stock, price_cents) values\n  ${values.join(",\n  ")};`,
  )
  lines.push("")
}

lines.push("commit;", "")
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"))
const published = products.filter((p) => p.published !== false).length
console.log(`Wrote ${categories.length} categories and ${products.length} products (${published} published).`)
