// The Nordaloom catalogue. `node scripts/build-seed.mjs` turns this into
// supabase/seed.sql.
//
// `images` are paths in the public "product-images" storage bucket, uploaded
// from owner-photos/ by scripts/upload-photos.mjs. Products with
// `published: false` have no photo yet: they stay in the database (the owner
// can see them) but are hidden from the shop until a photo is added.

export const C = {
  oat: { name: "Oat", hex: "#d9ccb4" },
  ecru: { name: "Undyed Ecru", hex: "#ede6d6" },
  fog: { name: "Fog Grey", hex: "#b9b8b0" },
  charcoal: { name: "Charcoal", hex: "#3e3d3b" },
  moss: { name: "Moss", hex: "#6b7358" },
  juniper: { name: "Juniper", hex: "#3f5245" },
  rust: { name: "Rust", hex: "#a45a3a" },
  rye: { name: "Rye", hex: "#b08a5a" },
  night: { name: "Night Blue", hex: "#2f3a4d" },
  plum: { name: "Heather Plum", hex: "#7a5a66" },
  birch: { name: "Birch", hex: "#cfc6b6" },
  lingon: { name: "Lingonberry", hex: "#8e2f36" },
  seaglass: { name: "Sea Glass", hex: "#a9b8b0" },
  baltic: { name: "Baltic Blue", hex: "#5d7488" },
  honey: { name: "Honey", hex: "#c99a4b" },
  // Colours seen in the owner's photos
  chestnut: { name: "Chestnut", hex: "#7b4a33" },
  forest: { name: "Forest Green", hex: "#3f5a3c" },
  pebble: { name: "Pebble", hex: "#cdc8bd" },
  amber: { name: "Amber", hex: "#c8922e" },
  camel: { name: "Camel", hex: "#a87c55" },
  teal: { name: "Deep Teal", hex: "#2f4a4d" },
  burgundy: { name: "Burgundy", hex: "#5b2327" },
  bottle: { name: "Bottle Green", hex: "#2f5146" },
  flecked: { name: "Flecked Oat", hex: "#d8d0c2" },
  taupe: { name: "Taupe", hex: "#9c8b74" },
  greyMelange: { name: "Grey Melange", hex: "#a9a8a2" },
  jade: { name: "Jade", hex: "#3f8a6e" },
  frost: { name: "Frost Grey", hex: "#d6d3cc" },
  lightGrey: { name: "Light Grey", hex: "#c9c7c2" },
  caramel: { name: "Caramel", hex: "#b07a4c" },
  pine: { name: "Pine Green", hex: "#2f4a36" },
  lilac: { name: "Heather Lilac", hex: "#9b8a96" },
  rose: { name: "Dusty Rose", hex: "#c9a79a" },
  grass: { name: "Grass Green", hex: "#3e7b3a" },
  cranberry: { name: "Cranberry", hex: "#b3232a" },
  sky: { name: "Sky Blue", hex: "#9db8e0" },
  navy: { name: "Navy", hex: "#2e3450" },
  stone: { name: "Stone Grey", hex: "#6f6a64" },
  mustard: { name: "Mustard", hex: "#c9a032" },
  ochre: { name: "Ochre", hex: "#b0782a" },
  graphite: { name: "Graphite", hex: "#5d5c58" },
}

export const categories = [
  {
    slug: "sweaters",
    name: "Sweaters",
    tagline: "The ones you reach for first",
    description:
      "Crewnecks, cables, rollnecks and chunky ribs. Cut to be worn for years and to soften with every winter.",
    image: "products/sweater-12.webp",
  },
  {
    slug: "cardigans",
    name: "Cardigans",
    tagline: "A layer for every room",
    description:
      "Buttoned, cropped, open and oversized — cardigans to wear over a shirt, a dress or another sweater from October to April.",
    image: "products/cardigan-05.webp",
  },
  {
    slug: "hats",
    name: "Hats",
    tagline: "Warm ears, all season",
    description: "Ribbed beanies and slouchy knits in the same yarns as our sweaters.",
    image: "products/hat-02.webp",
  },
  {
    slug: "scarves",
    name: "Scarves",
    tagline: "Wrapped twice, at least",
    description:
      "Long scarves, airy mohair and wide wraps generous enough to double as a shawl on a cold train platform.",
    image: "products/scarf-03.webp",
  },
  {
    slug: "mittens",
    name: "Mittens",
    tagline: "Warm hands, bright patterns",
    description:
      "Patterned mittens in the Latvian tradition — the one piece of knitwear where we let colour run wild.",
    image: "products/mittens-02.webp",
  },
  {
    slug: "socks",
    name: "Socks",
    tagline: "Made to be worn out",
    description: "Ribbed everyday socks, lace-cable socks and patterned pairs for a cold floor on a winter morning.",
    image: "products/socks-03.webp",
  },
  {
    slug: "blankets",
    name: "Blankets",
    tagline: "For long evenings",
    description:
      "Woven wool throws with fringed edges, and chunky knitted blankets heavy enough to feel like a hug.",
    image: "products/blanket-01.webp",
  },
]

const ADULT = ["XS", "S", "M", "L", "XL"]
const ONE = ["One size"]
const SOCKS = ["36–38", "39–41", "42–44", "45–47"]
const MITTENS = ["S/M", "M/L"]

const CARE_WOOL = [
  "Hand wash cold (max 30 °C) with a wool detergent",
  "Do not wring — press out water in a towel",
  "Dry flat, gently reshaped, away from direct heat",
  "Air between wears; remove pilling with a wool comb",
]
const CARE_MOHAIR = [
  "Hand wash cold (max 30 °C) with a wool detergent",
  "Dry flat and brush lightly once dry to lift the halo",
  "Fold, never hang",
  "Store with cedar or lavender between seasons",
]
const CARE_SOCKS = [
  "Machine wash on the wool cycle at 30 °C, inside out",
  "Do not tumble dry",
  "Dry flat or over a rail",
]
const CARE_BLANKET = [
  "Air outside regularly — wool rarely needs washing",
  "Spot clean with cold water where possible",
  "When needed, hand wash cold or dry clean",
  "Dry flat; do not tumble dry",
]
const CARE_CHUNKY = [
  "Spot clean only, with cold water and a little wool detergent",
  "Do not machine wash or soak — the loops will felt",
  "Shake out and air regularly; lay flat to store",
]

const SMALL_BATCH = "Knitted in small batches in Latvia"
const MADE_SMALL_BATCH = "Made in small batches in Latvia"

const img = (...names) => names.map((n) => `products/${n}.webp`)

export const products = [
  // --- Sweaters -------------------------------------------------------------
  {
    slug: "kapa-crewneck",
    category: "sweaters",
    name: "Kāpa Crewneck",
    short: "Our everyday raglan crewneck",
    description:
      "Named after the dunes along the Kurzeme coast, Kāpa is the sweater we'd keep if we could only have one. A clean raglan shape in smooth lambswool, with ribbed cuffs and hem and a neat round neckline that holds its form wash after wash.\n\nMid-weight and quietly warm, it sits as well under a coat in January as it does on its own on a cool May evening.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Regular fit — take your usual size", "Raglan sleeves, ribbed hem and cuffs", "Mid-weight, approx. 480 g (size M)", SMALL_BATCH],
    price: 159,
    colours: [C.chestnut, C.oat, C.charcoal, C.moss],
    sizes: ADULT,
    images: img("sweater-07"),
    featured: true,
  },
  {
    slug: "priede-fisherman-rollneck",
    category: "sweaters",
    name: "Priede Fisherman Rollneck",
    short: "Ribbed from rollneck to hem",
    description:
      "A proper cold-weather sweater. Priede is knitted in a fisherman rib from a soft, lightly spun wool that keeps its loft and shrugs off wind. The rollneck is deep enough to fold twice or pull up over your chin, and the body is long enough to tuck in.\n\nThe kind of sweater that replaces a jacket on a dry winter day.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["Relaxed, longer fit — size down for a closer fit", "Fisherman rib throughout", "Heavyweight, approx. 850 g (size M)", SMALL_BATCH],
    price: 198,
    colours: [C.ecru, C.juniper, C.charcoal],
    sizes: ADULT,
    images: img("sweater-08"),
    featured: true,
  },
  {
    slug: "gauja-cable-crew",
    category: "sweaters",
    name: "Gauja Cable Crew",
    short: "Three winding cables down the front",
    description:
      "The cables on Gauja twist and turn like the river it's named after: three deep cable panels down the front, framed by ribbing, in a round, full-bodied wool that gives every stitch real depth.\n\nA sweater with presence, cut with enough room in the body for a shirt underneath.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["Regular fit", "Three cable panels on the front, ribbed crew neck", "Heavyweight, approx. 780 g (size M)", SMALL_BATCH],
    price: 209,
    colours: [C.forest, C.ecru, C.oat],
    sizes: ADULT,
    images: img("sweater-09"),
  },
  {
    slug: "ezers-cable-crew",
    category: "sweaters",
    name: "Ezers Cable Crew",
    short: "All-over cables in a deep lake teal",
    description:
      "Ezers is covered in narrow braided cables from shoulder to hem, knitted in a dense wool the colour of a lake on a grey morning. The neck is a short, snug ribbed crew and the hem sits at the hip, so it looks as right with work trousers as with jeans.\n\nWarm enough to wear on its own on a cold, clear day.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Regular fit", "All-over braided cables", "Heavyweight, approx. 750 g (size M)", SMALL_BATCH],
    price: 215,
    colours: [C.teal, C.charcoal, C.oat],
    sizes: ADULT,
    images: img("sweater-02"),
  },
  {
    slug: "rudens-aran-sweater",
    category: "sweaters",
    name: "Rudens Aran Sweater",
    short: "Cables and diamonds in autumn burgundy",
    description:
      "Rudens (autumn) is our aran: cables, diamonds and textured panels worked across the whole front and down the sleeves, in a deep burgundy that looks almost black by candlelight.\n\nA heavy, generous sweater for the darkest months of the year.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["Relaxed fit", "Aran cables and diamond panels", "Heavyweight, approx. 900 g (size M)", SMALL_BATCH],
    price: 229,
    colours: [C.burgundy, C.ecru],
    sizes: ADULT,
    images: img("sweater-05"),
  },
  {
    slug: "suna-long-cable-sweater",
    category: "sweaters",
    name: "Sūna Long Cable Sweater",
    short: "Oversized and long, with a single cable",
    description:
      "Sūna (moss) is long, loose and very soft: an oversized sweater that falls to the upper thigh, with one cable running down the centre and dropped shoulders that let the sleeves pool at the wrist.\n\nWear it with leggings on a slow Sunday, or belted over a skirt.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Oversized, long fit — size down for less volume", "Central cable, dropped shoulders", "Mid-weight, approx. 620 g (size M)", SMALL_BATCH],
    price: 195,
    colours: [C.bottle, C.oat, C.fog],
    sizes: ADULT,
    images: img("sweater-03"),
    isNew: true,
  },
  {
    slug: "berzs-chunky-v-neck",
    category: "sweaters",
    name: "Bērzs Chunky V-Neck",
    short: "A chunky rib V-neck in undyed ecru",
    description:
      "Bērzs (birch) is a relaxed V-neck in a thick fisherman rib, knitted from undyed wool that keeps the soft, creamy colour of the fleece. The deep V sits comfortably over a T-shirt or a collar, and the long sleeves are made to be pushed up.\n\nChunky without being heavy.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Relaxed fit", "Fisherman rib, deep V-neck", "Mid-weight, approx. 600 g (size M)", SMALL_BATCH],
    price: 175,
    colours: [C.ecru, C.birch, C.night],
    sizes: ADULT,
    images: img("sweater-04"),
  },
  {
    slug: "smilga-fisherman-sweater",
    category: "sweaters",
    name: "Smilga Fisherman Sweater",
    short: "Oversized fisherman rib in flecked oat",
    description:
      "Smilga is named after the bent grass on the dunes, and its flecked oat colour comes from tiny darker fibres spun into the yarn. It's an oversized crew in a springy fisherman rib, with long sleeves and a soft, slightly rolled neckline.\n\nThe sweater to pull on first thing and forget you're wearing.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["Oversized fit — take your usual size for a slouchy look", "Fisherman rib, flecked yarn", "Mid-weight, approx. 680 g (size M)", SMALL_BATCH],
    price: 185,
    colours: [C.flecked, C.charcoal],
    sizes: ADULT,
    images: img("sweater-01"),
  },
  {
    slug: "rudzi-chunky-rib-sweater",
    category: "sweaters",
    name: "Rudzi Chunky Rib Sweater",
    short: "Boxy chunky rib with dropped shoulders",
    description:
      "Rudzi (rye) is a short, boxy sweater in a chunky rib, in the warm taupe of ripe rye. Dropped shoulders and wide sleeves give it an easy shape; turn the cuffs back once for the look in the photo.\n\nPairs well with high-waisted trousers and long skirts.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Boxy, slightly cropped fit", "Chunky rib, dropped shoulders", "Mid-weight, approx. 560 g (size M)", SMALL_BATCH],
    price: 169,
    colours: [C.taupe, C.ecru],
    sizes: ADULT,
    images: img("cardigan-01"),
  },
  {
    slug: "rits-merino-fine-knit",
    category: "sweaters",
    name: "Rīts Merino Fine Knit",
    short: "Fine-gauge merino for layering",
    description:
      "Rīts (morning) is a fine, smooth merino crewneck for days that start cold and end mild. Extra-fine fibres mean it sits comfortably against the skin, and the close knit keeps its shape under jackets and coats.\n\nIt's the sweater to wear to work, then on to dinner.",
    materials: "100% extra-fine merino wool",
    care: CARE_WOOL,
    details: ["Regular fit", "Fine gauge, ribbed crew neck", "Lightweight, approx. 260 g (size M)", SMALL_BATCH],
    price: 129,
    colours: [C.pebble, C.charcoal, C.baltic],
    sizes: ADULT,
    images: img("sweater-06"),
  },
  {
    slug: "dzintars-rib-crew",
    category: "sweaters",
    name: "Dzintars Rib Crew",
    short: "A relaxed rib crew in amber, ecru and camel",
    description:
      "Named for Baltic amber, Dzintars is a relaxed crewneck in a soft fisherman rib, knitted in three warm colours: amber, undyed ecru and camel. The rib gives it stretch and bounce, and the dropped shoulders make it easy to layer over a shirt.\n\nThe colours are dyed to sit well together, so they're often bought in pairs.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Relaxed fit", "Fisherman rib, ribbed crew neck", "Mid-weight, approx. 540 g (size M)", SMALL_BATCH],
    price: 179,
    colours: [C.amber, C.ecru, C.camel],
    sizes: ADULT,
    images: img("sweater-11", "sweater-10"),
    featured: true,
    isNew: true,
  },

  // --- Cardigans ------------------------------------------------------------
  {
    slug: "liepa-classic-cardigan",
    category: "cardigans",
    name: "Liepa Classic Cardigan",
    short: "The buttoned cardigan, done properly",
    description:
      "Liepa is our take on the cardigan everyone should own: a soft, slightly brushed grey melange with ribbed sleeves, a reinforced button band that won't sag and dark tortoiseshell-effect buttons.\n\nIt's the layer we reach for from October to April, over a shirt, a dress or another sweater.",
    materials: "Lambswool blend; tortoiseshell-effect buttons",
    care: CARE_WOOL,
    details: ["Regular fit", "Button front, ribbed sleeves", "Mid-weight, approx. 500 g (size M)", SMALL_BATCH],
    price: 179,
    colours: [C.greyMelange, C.oat, C.charcoal, C.lingon],
    sizes: ADULT,
    images: img("cardigan-03"),
    featured: true,
  },
  {
    slug: "abele-openwork-cardigan",
    category: "cardigans",
    name: "Ābele Openwork Cardigan",
    short: "A V-neck with an openwork leaf pattern",
    description:
      "A soft V-neck cardigan with an openwork pattern of small leaves climbing up the body, like an apple tree coming into leaf. Ābele is knitted in a fine, slightly fuzzy wool in a deep jade green, with ribbed cuffs and hem.\n\nPretty enough for a summer wedding, warm enough for a northern one.",
    materials: "100% merino wool",
    care: CARE_WOOL,
    details: ["Regular fit", "Openwork leaf pattern, V-neck", "Lightweight, approx. 320 g (size M)", SMALL_BATCH],
    price: 169,
    colours: [C.jade, C.ecru, C.birch],
    sizes: ADULT,
    images: img("cardigan-04"),
  },
  {
    slug: "vakars-cropped-cardigan",
    category: "cardigans",
    name: "Vakars Cropped Cardigan",
    short: "Chunky rib, cropped, with big sleeves",
    description:
      "A cropped cardigan in a chunky fisherman rib, with a deep V-neck, five dark buttons and generous balloon sleeves gathered into a ribbed cuff. Vakars sits at the waist, so it's easy over dresses and high-waisted skirts.\n\nMade for evenings by the sea when the wind picks up.",
    materials: "100% lambswool; dark corozo buttons",
    care: CARE_WOOL,
    details: ["Cropped fit", "Fisherman rib, five buttons, full sleeves", "Mid-weight, approx. 520 g (size M)", SMALL_BATCH],
    price: 175,
    colours: [C.frost, C.ecru, C.plum],
    sizes: ADULT,
    images: img("cardigan-05"),
    isNew: true,
  },
  {
    slug: "egle-oversized-cardigan",
    category: "cardigans",
    name: "Egle Oversized Cardigan",
    short: "An open, oversized rib cardigan",
    description:
      "A long, loose cardigan in a chunky rib that's made to be worn open and slipping off one shoulder. Egle has no buttons — just a wide ribbed front band that falls in soft folds — and sleeves long enough to pull over your hands.\n\nThe kind of cardigan that ends up being worn instead of a coat.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["Oversized fit", "Open front, wide ribbed band", "Heavyweight, approx. 850 g (size M)", SMALL_BATCH],
    price: 229,
    colours: [C.lightGrey, C.oat, C.juniper],
    sizes: ADULT,
    images: img("cardigan-06"),
  },
  {
    slug: "mezs-long-cardigan",
    category: "cardigans",
    name: "Mežs Long Cardigan",
    short: "Knee-length, with a tie belt",
    description:
      "Mežs is almost a coat. It falls just above the knee, has deep side pockets and a knitted belt you can tie or leave out. The double-knit front panels stay flat and smooth, while the sleeves are ribbed for a close cuff.\n\nMade for forest walks, quiet Sunday mornings and everything between.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Relaxed, long fit", "Removable tie belt, side pockets", "Heavyweight, approx. 900 g (size M)", SMALL_BATCH],
    price: 229,
    colours: [C.moss, C.oat, C.charcoal],
    sizes: ADULT,
    published: false,
  },
  {
    slug: "vejs-zip-cardigan",
    category: "cardigans",
    name: "Vējš Zip Cardigan",
    short: "A zip-through knit with a stand collar",
    description:
      "Vējš (wind) is a sturdy, zip-through cardigan with a high stand collar and a two-way zip. The textured half-cardigan stitch makes it thick and springy without being heavy.\n\nOur favourite for cycling, the seaside and anything outdoors.",
    materials: "100% lambswool; two-way metal zip",
    care: CARE_WOOL,
    details: ["Regular fit", "Two-way zip, stand collar", "Mid-weight, approx. 640 g (size M)", SMALL_BATCH],
    price: 199,
    colours: [C.charcoal, C.night, C.rye],
    sizes: ADULT,
    published: false,
  },
  {
    slug: "sniegs-mohair-cardigan",
    category: "cardigans",
    name: "Sniegs Mohair Cardigan",
    short: "An airy mohair cardigan with a cloud-soft halo",
    description:
      "Sniegs is loose, light and a little bit dreamy. Kid mohair and merino are knitted together at an open gauge for a cardigan that floats rather than clings, with oversized buttons to match.\n\nThrow it over everything.",
    materials: "70% kid mohair, 30% merino wool; corozo buttons",
    care: CARE_MOHAIR,
    details: ["Oversized fit", "Open gauge, five large buttons", "Lightweight, approx. 300 g (size M)", SMALL_BATCH],
    price: 189,
    colours: [C.ecru, C.fog, C.honey],
    sizes: ADULT,
    published: false,
  },

  // --- Hats -----------------------------------------------------------------
  {
    slug: "kapa-rib-beanie",
    category: "hats",
    name: "Kāpa Rib Beanie",
    short: "Classic ribbed beanie with a deep turn-up",
    description:
      "A simple ribbed beanie in soft lambswool. The long body folds into a double-layer turn-up over the ears, and the crown is shaped so it sits softly rather than peaks.\n\nThe hat we give to friends — usually in rust.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["One size, fits most adults", "Double-layer turn-up", SMALL_BATCH],
    price: 45,
    colours: [C.rust, C.oat, C.charcoal, C.moss],
    sizes: ONE,
    images: img("hat-03"),
  },
  {
    slug: "priede-turn-up-beanie",
    category: "hats",
    name: "Priede Turn-Up Beanie",
    short: "A soft caramel beanie with a wide cuff",
    description:
      "A close-fitting beanie in a fine rib, with a wide turn-up that sits just above the eyebrows. Priede is knitted in a soft, slightly brushed wool that doesn't itch at the forehead, in a warm caramel that suits almost everyone.\n\nFold it once, pull it down, done.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["One size, fits most adults", "Fine rib, wide turn-up", SMALL_BATCH],
    price: 49,
    colours: [C.caramel, C.ecru, C.juniper, C.charcoal],
    sizes: ONE,
    images: img("hat-02", "hat-05"),
    featured: true,
  },
  {
    slug: "egle-slouch-beanie",
    category: "hats",
    name: "Egle Slouch Beanie",
    short: "Chunky and slouchy, in pine green",
    description:
      "A chunky slouch beanie with deep ridges knitted in bands from brim to crown, so it gathers softly at the back of the head. Egle is thick and warm, in a dark pine green that looks good against every colour of hair.\n\nFor windy hilltops and long walks home.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["One size, fits most adults", "Slouchy fit, ridged bands", SMALL_BATCH],
    price: 55,
    colours: [C.pine, C.oat, C.charcoal],
    sizes: ONE,
    images: img("hat-01"),
  },
  {
    slug: "jura-merino-watch-cap",
    category: "hats",
    name: "Jūra Merino Watch Cap",
    short: "Fine merino cap for milder days",
    description:
      "A fine, close-fitting watch cap in extra-fine merino. Jūra is thin enough to wear for a run or under a hood, and breathes well on autumn days that can't decide what they are.\n\nNo itch, no fuss.",
    materials: "100% extra-fine merino wool",
    care: CARE_WOOL,
    details: ["One size, fits most adults", "Fine rib, close fit", SMALL_BATCH],
    price: 39,
    colours: [C.night, C.charcoal, C.seaglass, C.lingon],
    sizes: ONE,
    published: false,
  },
  {
    slug: "salna-star-hat",
    category: "hats",
    name: "Salna Star Hat",
    short: "Colourwork hat with a wool pompom",
    description:
      "A star pattern borrowed from old Latvian mittens, knitted around a warm, double-layered hat and finished with a big wool pompom. Because it's stranded in two colours, it's twice as warm as a plain knit.\n\nLined with a fine merino band at the forehead for comfort.",
    materials: "100% lambswool; merino inner band",
    care: CARE_WOOL,
    details: ["One size, fits most adults", "Two-colour stranded knit, pompom", SMALL_BATCH],
    price: 59,
    colours: [
      { name: "Ecru / Night Blue", hex: "#ede6d6" },
      { name: "Charcoal / Oat", hex: "#3e3d3b" },
    ],
    sizes: ONE,
    published: false,
  },
  {
    slug: "puce-earflap-hat",
    category: "hats",
    name: "Pūce Earflap Hat",
    short: "Earflaps and braided ties for real winter",
    description:
      "For the coldest days of the year. Pūce has knitted earflaps with braided ties, a doubled brim and a wool pompom on top. Knitted in a thick lambswool that shrugs off snow.\n\nNamed after the owl, who is always wise enough to stay warm.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["One size, fits most adults", "Earflaps with braided ties", SMALL_BATCH],
    price: 65,
    colours: [C.charcoal, C.oat, C.rust],
    sizes: ONE,
    published: false,
  },

  // --- Scarves --------------------------------------------------------------
  {
    slug: "egle-chunky-wrap",
    category: "scarves",
    name: "Egle Chunky Wrap",
    short: "An oversized wrap that doubles as a shawl",
    description:
      "Wide enough to wear over the shoulders as a shawl, long enough to wrap twice as a scarf. Egle is knitted in a chunky oat wool with deep horizontal ridges that give it an almost woven look.\n\nFor cold trains, big coats and sitting outside long after the sun has gone.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["Approx. 60 × 210 cm", "Chunky ridged texture", SMALL_BATCH],
    price: 125,
    colours: [C.oat, C.ecru, C.juniper],
    sizes: ONE,
    images: img("scarf-03"),
    featured: true,
  },
  {
    slug: "migla-mohair-scarf",
    category: "scarves",
    name: "Migla Mohair Scarf",
    short: "A cloud of brushed mohair",
    description:
      "A wide, feather-light scarf in brushed mohair and merino, knitted in a soft garter stitch. It bunches beautifully at the neck and weighs almost nothing in a bag.\n\nThe softest thing we make, and the one most often bought as a gift.",
    materials: "70% kid mohair, 30% merino wool",
    care: CARE_MOHAIR,
    details: ["Approx. 40 × 190 cm", "Airy garter stitch", SMALL_BATCH],
    price: 89,
    colours: [C.ecru, C.fog, C.honey],
    sizes: ONE,
    images: img("scarf-05"),
  },
  {
    slug: "kapa-long-scarf",
    category: "scarves",
    name: "Kāpa Long Scarf",
    short: "A long, soft scarf in forest green",
    description:
      "A long, generous scarf in soft lambswool, knitted to a full 220 cm so it can go round twice and still hang to the waist. Kāpa is plain and dense, in a dark forest green that goes with every winter coat.\n\nSimple and warm — the scarf that stays by the door.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Approx. 35 × 220 cm", "Smooth stocking stitch", SMALL_BATCH],
    price: 85,
    colours: [C.forest, C.oat, C.charcoal],
    sizes: ONE,
    images: img("scarf-02"),
  },
  {
    slug: "virsi-garter-scarf",
    category: "scarves",
    name: "Virši Garter Scarf",
    short: "Garter stitch in heather lilac",
    description:
      "Virši means heather, and this scarf has its colour: a soft, dusty lilac with flecks of grey. It's knitted in a squishy garter stitch that looks the same on both sides and never curls at the edges.\n\nA gentle colour for grey days.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Approx. 30 × 190 cm", "Reversible garter stitch", SMALL_BATCH],
    price: 79,
    colours: [C.lilac, C.fog, C.oat],
    sizes: ONE,
    images: img("scarf-04"),
    isNew: true,
  },
  {
    slug: "sarts-chunky-scarf",
    category: "scarves",
    name: "Sārts Chunky Scarf",
    short: "A thick seed-stitch scarf in dusty rose",
    description:
      "A thick, cosy scarf in a chunky seed stitch, knitted from a plump wool in a soft dusty rose. The bobbly texture traps warmth and holds its shape however you wrap it.\n\nSārts means rosy — which is what your cheeks will be after a walk in the frost.",
    materials: "100% Nordic wool",
    care: CARE_WOOL,
    details: ["Approx. 28 × 180 cm", "Chunky seed stitch", SMALL_BATCH],
    price: 95,
    colours: [C.rose, C.oat],
    sizes: ONE,
    images: img("scarf-01"),
  },
  {
    slug: "lietus-woven-scarf",
    category: "scarves",
    name: "Lietus Woven Scarf",
    short: "A soft woven wool scarf with fringed ends",
    description:
      "A wide, soft scarf woven from brushed wool and finished with a long fringe at each end. Lietus (rain) is lighter than our knitted scarves and drapes beautifully — wrap it loosely or wear it long over a dark coat.\n\nIt softens noticeably after the first few wears.",
    materials: "100% lambswool",
    care: ["Hand wash cold (max 30 °C) with a wool detergent", "Dry flat", "Comb the fringe gently once dry"],
    details: ["Approx. 50 × 190 cm plus fringe", "Woven, brushed finish", MADE_SMALL_BATCH],
    price: 89,
    colours: [C.grass, C.charcoal, C.oat],
    sizes: ONE,
    images: img("scarf-06"),
  },

  // --- Mittens --------------------------------------------------------------
  {
    slug: "sniegs-snowflake-mittens",
    category: "mittens",
    name: "Sniegs Snowflake Mittens",
    short: "Chunky snowflake mittens in red and ecru",
    description:
      "Big, warm mittens with a band of white snowflakes on a red ground, bordered with stripes and small diamonds, and a long ribbed ecru cuff to tuck into your sleeves. Sniegs (snow) is knitted in a thick wool, stranded in two colours for double warmth.\n\nMade for snowball fights and mugs of something hot.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Chunky stranded colourwork", "Long ribbed cuff", SMALL_BATCH],
    price: 49,
    colours: [{ name: "Red / Ecru", hex: "#b3232a" }],
    sizes: MITTENS,
    images: img("mittens-02"),
    featured: true,
    isNew: true,
  },
  {
    slug: "plava-flower-mittens",
    category: "mittens",
    name: "Pļava Flower Mittens",
    short: "Daisies on dark brown, with a green cuff",
    description:
      "Pļava (meadow) mittens carry a pattern of white daisies with golden centres on a dark bark-brown ground, finished with a green ribbed cuff. Stranded colourwork makes the fabric dense and wind-resistant, and every pair is a little different where the flowers meet the thumb.\n\nA summer meadow for the middle of winter.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Fine stranded colourwork", "Ribbed cuff in a contrast colour", SMALL_BATCH],
    price: 58,
    colours: [{ name: "Bark / Ecru", hex: "#4e4038" }],
    sizes: MITTENS,
    images: img("mittens-03"),
    isNew: true,
  },
  {
    slug: "migla-cable-mittens",
    category: "mittens",
    name: "Migla Cable Mittens",
    short: "Cables and seed stitch in stone grey",
    description:
      "Soft grey mittens with a single leafy cable framed by seed stitch, and a neat ribbed cuff. Migla (fog) is knitted in a fine lambswool that's warm without being bulky, so you can still hold keys and tickets.\n\nQuiet mittens for every day.",
    materials: "100% lambswool",
    care: CARE_WOOL,
    details: ["Cable and seed stitch", "Ribbed cuff", SMALL_BATCH],
    price: 45,
    colours: [C.stone, C.oat],
    sizes: MITTENS,
    images: img("mittens-01"),
  },

  // --- Socks ----------------------------------------------------------------
  {
    slug: "ezers-rib-socks",
    category: "socks",
    name: "Ezers Rib Socks",
    short: "Long rib socks in cranberry, sky and navy",
    description:
      "Our everyday sock: a long, soft rib that reaches to mid-calf and stays up without pinching. Ezers comes in cranberry red, sky blue and navy, and is knitted from wool with a little polyamide for strength at the heel and toe.\n\nWarm in winter boots, breathable in trainers.",
    materials: "75% merino wool, 25% polyamide",
    care: CARE_SOCKS,
    details: ["Mid-calf length", "Rib throughout, reinforced heel and toe", SMALL_BATCH],
    price: 24,
    colours: [C.cranberry, C.sky, C.navy],
    sizes: SOCKS,
    images: img("socks-03", "socks-02", "socks-04"),
    featured: true,
  },
  {
    slug: "meness-lace-cable-socks",
    category: "socks",
    name: "Mēness Lace-Cable Socks",
    short: "Lace and cables in stone grey",
    description:
      "Fine socks with a pattern of lace and small cables running from cuff to toe, in a soft stone grey. Mēness (moon) socks are thin enough for shoes and pretty enough to show off with a cropped trouser.\n\nThe pair people ask about.",
    materials: "75% merino wool, 25% polyamide",
    care: CARE_SOCKS,
    details: ["Mid-calf length", "Lace-cable pattern", SMALL_BATCH],
    price: 34,
    colours: [C.stone, C.ecru],
    sizes: SOCKS,
    images: img("socks-01"),
  },
  {
    slug: "salna-pattern-socks",
    category: "socks",
    name: "Salna Pattern Socks",
    short: "Snowflake pattern with bright blue heels",
    description:
      "Short, patterned socks with blue snowflakes and small diamonds on an ecru ground, and bright cornflower-blue cuffs, heels and toes. Stranded colourwork doubles the thickness, so these are properly warm — the pair for a cold floor on a winter morning.\n\nThey make a very good present.",
    materials: "80% wool, 20% polyamide",
    care: CARE_SOCKS,
    details: ["Ankle length", "Two-colour stranded pattern, contrast heel and toe", SMALL_BATCH],
    price: 32,
    colours: [{ name: "Ecru / Cornflower", hex: "#ede6d6" }],
    sizes: SOCKS,
    images: img("socks-05"),
    isNew: true,
  },
  {
    slug: "upe-everyday-wool-socks",
    category: "socks",
    name: "Upe Everyday Wool Socks",
    short: "Everyday wool socks, reinforced where it counts",
    description:
      "Upe is knitted from wool with a little nylon for strength, reinforced at the heel and toe, and finished with a soft rib cuff that stays up without pinching.\n\nWarm in winter boots, breathable in trainers.",
    materials: "80% wool, 20% polyamide",
    care: CARE_SOCKS,
    details: ["Mid-calf length", "Reinforced heel and toe", SMALL_BATCH],
    price: 22,
    colours: [C.moss, C.oat, C.charcoal],
    sizes: SOCKS,
    published: false,
  },
  {
    slug: "mezs-boot-socks",
    category: "socks",
    name: "Mežs Boot Socks",
    short: "Thick cushioned socks for walking boots",
    description:
      "Thick, cushioned boot socks with a terry-knit sole for long walks and wet forest paths. The leg is ribbed and long enough to fold over the top of a boot.\n\nWool stays warm even when damp, which is exactly the point.",
    materials: "75% wool, 25% polyamide",
    care: CARE_SOCKS,
    details: ["Knee-high, fold-over cuff", "Cushioned terry sole", SMALL_BATCH],
    price: 29,
    colours: [C.moss, C.charcoal, C.oat],
    sizes: SOCKS,
    published: false,
  },
  {
    slug: "sniegs-alpaca-bed-socks",
    category: "socks",
    name: "Sniegs Alpaca Bed Socks",
    short: "Soft alpaca socks for cold nights",
    description:
      "Loose, very soft bed socks in brushed alpaca. They have a relaxed cuff that won't leave marks and a slightly fuzzy finish that feels lovely on bare skin.\n\nFor cold nights and slow mornings.",
    materials: "60% baby alpaca, 40% wool",
    care: ["Hand wash cold (max 30 °C) with a wool detergent", "Dry flat", "Do not tumble dry"],
    details: ["Ankle length, relaxed cuff", "Brushed finish", SMALL_BATCH],
    price: 28,
    colours: [C.ecru, C.honey, C.fog],
    sizes: SOCKS,
    published: false,
  },

  // --- Blankets -------------------------------------------------------------
  {
    slug: "salna-diamond-throw",
    category: "blankets",
    name: "Salna Diamond Throw",
    short: "Woven diamonds in rust, mustard and ochre",
    description:
      "A soft woven wool throw with a pattern of small diamonds, like frost on a window. Salna comes in rust with ecru diamonds, mustard and ochre — warm autumn colours that look even better stacked together.\n\nHeavy enough for a bed in winter, and made to be handed down.",
    materials: "100% lambswool",
    care: CARE_BLANKET,
    details: ["Woven diamond pattern", "Approx. 1.4 kg (throw size)", MADE_SMALL_BATCH],
    price: 189,
    colours: [{ name: "Rust / Ecru", hex: "#a45a3a" }, C.mustard, C.ochre],
    sizes: ["Throw 130 × 170 cm", "Large 150 × 200 cm"],
    sizePrices: { "Large 150 × 200 cm": 239 },
    images: img("blanket-01"),
    featured: true,
  },
  {
    slug: "jura-fringed-throw",
    category: "blankets",
    name: "Jūra Fringed Throw",
    short: "Soft blue woven wool with a long fringe",
    description:
      "A light, soft throw woven in a blue-grey wool with a subtle texture, finished with a long fringe on every edge. Jūra (sea) adds warmth without weight — fold it at the foot of the bed or pull it over your shoulders on a cool evening.\n\nThe colour shifts from grey to blue with the light.",
    materials: "100% lambswool",
    care: CARE_BLANKET,
    details: ["Woven, fringed edges", "Approx. 0.9 kg", MADE_SMALL_BATCH],
    price: 169,
    colours: [C.baltic, C.fog],
    sizes: ["Throw 130 × 170 cm"],
    images: img("blanket-02"),
    isNew: true,
  },
  {
    slug: "mezs-herringbone-throw",
    category: "blankets",
    name: "Mežs Herringbone Throw",
    short: "Graphite herringbone with a knotted fringe",
    description:
      "A classic herringbone and diamond twill in graphite and pale grey, woven from a sturdy wool and finished with a fringe at both ends. Mežs is the throw for the reading chair and the end of the sofa — the one you pull over your feet without thinking.\n\nIt only gets softer with use.",
    materials: "100% lambswool",
    care: CARE_BLANKET,
    details: ["Woven herringbone twill, fringed ends", "Approx. 1.3 kg", MADE_SMALL_BATCH],
    price: 179,
    colours: [C.graphite, C.oat],
    sizes: ["Throw 130 × 170 cm"],
    images: img("blanket-03"),
  },
  {
    slug: "priede-chunky-knit-throw",
    category: "blankets",
    name: "Priede Chunky Knit Throw",
    short: "Giant loops of pine-green merino",
    description:
      "A statement blanket knitted in giant loops of soft, unspun merino, in a deep pine green. Priede is heavy, squishy and wonderfully warm — lay it over the bed or across the sofa and it becomes the most-touched thing in the room.\n\nEach one is knitted loop by loop, so no two are quite the same.",
    materials: "100% merino wool (unspun)",
    care: CARE_CHUNKY,
    details: ["Chunky knitted loops", "Approx. 2.5 kg", SMALL_BATCH],
    price: 249,
    colours: [C.pine, C.oat, C.charcoal],
    sizes: ["Throw 120 × 150 cm", "Large 150 × 200 cm"],
    sizePrices: { "Large 150 × 200 cm": 329 },
    images: img("blanket-04"),
  },
  {
    slug: "kapa-knitted-throw",
    category: "blankets",
    name: "Kāpa Knitted Throw",
    short: "A fine-knit grey throw for every day",
    description:
      "A simple, fine-knit throw in grey melange lambswool with a neat edge. Kāpa is light enough to leave on the sofa all year and fold into a neat square when guests come.\n\nOur most practical blanket.",
    materials: "100% lambswool",
    care: CARE_BLANKET,
    details: ["Fine knit with neat edges", "Approx. 1.1 kg", SMALL_BATCH],
    price: 149,
    colours: [C.greyMelange, C.oat],
    sizes: ["Throw 130 × 170 cm"],
    images: img("blanket-05"),
  },
  {
    slug: "rits-merino-baby-blanket",
    category: "blankets",
    name: "Rīts Merino Baby Blanket",
    short: "Soft merino for the smallest ones",
    description:
      "A small, soft blanket in extra-fine merino, knitted in a gentle seed stitch with a garter border. Rīts is breathable, naturally temperature-regulating and gentle on new skin.\n\nOften bought as a welcome gift — and usually kept long after it's outgrown.",
    materials: "100% extra-fine merino wool",
    care: ["Machine wash on the wool cycle at 30 °C", "Dry flat", "Do not tumble dry"],
    details: ["Approx. 80 × 100 cm", "Seed stitch with garter border", SMALL_BATCH],
    price: 95,
    colours: [C.ecru, C.seaglass, C.oat],
    sizes: ONE,
    published: false,
  },
  {
    slug: "gauja-striped-picnic-blanket",
    category: "blankets",
    name: "Gauja Striped Picnic Blanket",
    short: "Wide stripes for grass, sand and sofa",
    description:
      "A sturdy, tightly knitted blanket in wide stripes, made for picnics by the river and cool evenings on the beach. Gauja is dense enough to sit on and washes well.\n\nComes rolled with a cotton carry strap.",
    materials: "100% lambswool; cotton carry strap",
    care: CARE_BLANKET,
    details: ["Dense knit, wide stripes", "Approx. 1.6 kg, with carry strap", SMALL_BATCH],
    price: 189,
    colours: [
      { name: "Oat / Rust", hex: "#d9ccb4" },
      { name: "Baltic / Ecru", hex: "#5d7488" },
    ],
    sizes: ["Throw 130 × 170 cm"],
    published: false,
  },
]
